/**
 * Loads and caches character .glb models for use as player meshes.
 *
 * IMPORTANT — Asset Pipeline:
 *   Production models are optimized .glb files generated from .vox sources
 *   by the CI model conversion pipeline (scripts/convert-models.sh).
 *   The GLTFLoader is the PRIMARY and PREFERRED loader.
 *
 *   In development only, if a .glb is missing, a fallback attempts to load
 *   the .vox file directly via VoxLoader. This fallback exists solely to
 *   unblock local development when the conversion pipeline hasn't been run.
 *   It logs loud warnings so the issue is visible.
 *
 *   DO NOT remove the GLTFLoader path or make VoxLoader the primary loader.
 *   See CLAUDE.md "Asset Pipeline" section for details.
 */

import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { loadVoxModel } from './VoxLoader';

export type CharacterModelId = 'simple' | 'owl';

/** Resolved base path for static assets (handles Vite base config). */
function assetBase(): string {
  return import.meta.env.BASE_URL ?? '/';
}

const MODEL_PATHS: Record<Exclude<CharacterModelId, 'simple'>, { glb: string; vox: string }> = {
  owl: {
    glb: 'assets/characters/owl.glb',
    vox: 'assets/characters/owl.vox',
  },
};

const loader = new GLTFLoader();
const cache = new Map<string, THREE.Group>();

/**
 * Try loading a .glb file. Returns the scene group or null on failure.
 * Logs detailed error information when loading fails.
 */
function loadGlb(url: string): Promise<THREE.Group | null> {
  return new Promise<THREE.Group | null>((resolve) => {
    loader.load(
      url,
      (gltf) => {
        const scene = gltf.scene;
        scene.traverse((child) => {
          if (child instanceof THREE.Mesh) {
            child.castShadow = true;
          }
        });
        console.log(`[CharacterModelLoader] Loaded .glb model from ${url}`);
        resolve(scene);
      },
      undefined,
      (error) => {
        console.error(
          `[CharacterModelLoader] Failed to load .glb model from ${url}.`,
          `This likely means the model conversion pipeline has not been run.`,
          `Run: ./scripts/convert-models.sh`,
          `Or trigger the "Convert Character Models" GitHub Actions workflow.`,
          error,
        );
        resolve(null);
      },
    );
  });
}

/**
 * Load a character model by ID.
 * Returns a *clone* of the cached scene graph so each caller gets its own instance.
 * Returns `null` for the built-in 'simple' model (caller uses default box).
 *
 * Loads .glb (optimized) models via GLTFLoader. In development mode only,
 * falls back to parsing .vox directly with a loud warning.
 */
export async function loadCharacterModel(id: CharacterModelId): Promise<THREE.Group | null> {
  if (id === 'simple') return null;

  const paths = MODEL_PATHS[id];
  const base = assetBase();
  const cacheKey = id;

  // Return cloned cached model
  const cached = cache.get(cacheKey);
  if (cached) return cached.clone();

  // Try .glb first (this is the expected production path)
  const glbUrl = base + paths.glb;
  let group = await loadGlb(glbUrl);

  // Dev-only fallback: try .vox with loud warning
  if (!group) {
    const isDev = import.meta.env.DEV;
    if (isDev) {
      console.warn(
        `[CharacterModelLoader] DEV FALLBACK: Attempting .vox load for "${id}".`,
        `This is a development-only fallback. In production, .glb files must be`,
        `generated by the CI pipeline. Run: ./scripts/convert-models.sh`,
      );
      const voxUrl = base + paths.vox;
      try {
        group = await loadVoxModel(voxUrl);
        console.warn(
          `[CharacterModelLoader] Loaded "${id}" from .vox (dev fallback).`,
          `Performance will be worse than the optimized .glb format.`,
        );
      } catch (err) {
        console.error(
          `[CharacterModelLoader] Failed to load "${id}" from both .glb and .vox:`,
          err,
        );
        return null;
      }
    } else {
      console.error(
        `[CharacterModelLoader] PRODUCTION ERROR: .glb model "${id}" not found at ${glbUrl}.`,
        `The model conversion pipeline may not have run during deployment.`,
        `Check the "Convert Character Models" step in the deploy workflow.`,
      );
      return null;
    }
  }

  cache.set(cacheKey, group);
  return group.clone();
}
